@startuml

:Visiteur anonyme: as Va
:Utilisateur connecte: as Uc
:Administrateur : as adm


Va --> (Création d'un compte Utilisateur)
Uc --> (Gestion d'un compte utilisateur)
Uc --> (Réinitialisation de son mot de passe)
adm --> (Création et gestion de comptes utilisateurs et administrateurs)
adm --> (Désactivation et suppression d'un compte utilisateur)





@enduml

